name: SimpleAuth
main: SimpleAuth\SimpleAuth
version: 1.7.0
api: 1.8.0
load: STARTUP
author: PocketMine Team
authors: [shoghicp]
description: Prevents people to impersonate an account, requering registration and login when connecting.
website: https://github.com/PocketMine/SimpleAuth
commands:
 login:
  description: "Logs into an account"
  usage: "/login <password>"
 register:
  description: "Registers an account"
  usage: "/register <password>"

permissions:
 simpleauth:
  default: op
  description: "Allows using everything SimpleAuth has"
  children:
   simpleauth.chat:
    description: "Allows using the chat while not being authenticated"
    default: false
   simpleauth.move:
    description: "Allows moving while not being authenticated"
    default: false
   simpleauth.lastip:
    description: "Allows authenticating using the lastIP when enabled in the config"
    default: notop
   simpleauth.command:
    description: "Allows using SimpleAuth commands"
    default: true
